INSERT INTO Projects (
    internshipposition_id, 
    supervisor_id, 
    project_url, 
    project_name_en, 
    project_name_fr, 
    description_en, 
    description_fr, 
    status
) VALUES 
(1, 1, NULL, 
    'AI-Enhanced Visual Storytelling Platform', 
    'Plateforme de narration visuelle améliorée par l IA', 
    'Revolutionize content creation with an AI-powered platform that allows users to generate interactive visual stories. Utilizing advanced machine learning algorithms, automated video editing, and intelligent enhancements, this platform empowers small businesses and individual creators to produce impactful multimedia content effortlessly.', 
    'Révolutionnez la création de contenu avec une plateforme alimentée par l IA permettant aux utilisateurs de générer des histoires visuelles interactives. En utilisant des algorithmes avancés d apprentissage automatique, un montage vidéo automatisé et des améliorations intelligentes, cette plateforme permet aux petites entreprises et aux créateurs individuels de produire facilement du contenu multimédia percutant.', 
    'Pending'),
(1, 1, NULL, 
    'Community Heritage Preservation', 
    'Préservation du patrimoine communautaire', 
    'Collaborate with local communities to document and digitize cultural practices using cutting-edge photography and videography. This project aims to create a rich digital archive, promoting cultural appreciation and preserving endangered traditions through advanced digital asset management systems.', 
    'Collaborez avec les communautés locales pour documenter et numériser les pratiques culturelles en utilisant la photographie et la vidéographie de pointe. Ce projet vise à créer une archive numérique riche, promouvant l appréciation culturelle et préservant les traditions menacées grâce à des systèmes avancés de gestion des actifs numériques.', 
    'Pending'),
(1, 1, NULL, 
    'Interactive Educational Video Series', 
    'Série de vidéos éducatives interactives', 
    'Develop an engaging and accessible video series for underserved communities, focusing on STEM and the arts. Incorporating interactive elements, data-driven adaptive learning techniques, and narrative-based storytelling, this project bridges educational gaps with creativity and innovation.', 
    'Développez une série de vidéos engageantes et accessibles pour les communautés mal desservies, axée sur les STEM et les arts. En intégrant des éléments interactifs, des techniques d apprentissage adaptatives basées sur les données et une narration axée sur les histoires, ce projet comble les lacunes éducatives avec créativité et innovation.', 
    'Pending'),
(1, 1, NULL, 
    'Global Language Learning Platform', 
    'Plateforme mondiale dapprentissage des langues', 
    'Develop a platform where users can learn languages through culturally relevant stories and multimedia.', 
    'Développez une plateforme où les utilisateurs peuvent apprendre des langues grâce à des histoires culturellement pertinentes et à des contenus multimédias.', 
    'Pending'),
(1, 1, NULL, 
    'AI-Driven Content Ideation Tool', 
    'Outil de génération d idées de contenu alimenté par l IA', 
    'Build a tool that uses AI to suggest content ideas based on trends and user interests.', 
    'Créez un outil qui utilise l IA pour suggérer des idées de contenu basées sur les tendances et les intérêts des utilisateurs.', 
    'Pending'),
(1, 1, NULL, 
    'Digital Sustainability Hub', 
    'Centre numérique de durabilité', 
    'Create a platform for sharing sustainability-related content, including blogs, videos, and tutorials.', 
    'Créez une plateforme pour partager du contenu lié à la durabilité, y compris des blogs, des vidéos et des tutoriels.', 
    'Pending'),
(2, 1, NULL, 
    'Virtual Reality Education Platform', 
    'Plateforme éducative de réalité virtuelle', 
    'Create a cutting-edge virtual reality platform designed for immersive educational experiences. With features such as interactive virtual field trips and hands-on simulation labs, this platform integrates advanced AR/VR technologies to revolutionize experiential learning.', 
    'Créez une plateforme de réalité virtuelle de pointe conçue pour des expériences éducatives immersives. Avec des fonctionnalités telles que des excursions virtuelles interactives et des laboratoires de simulation pratiques, cette plateforme intègre des technologies AR/VR avancées pour révolutionner l apprentissage expérientiel.', 
    'Pending'),
(2, 1, NULL, 
    'AR Navigation System for Museums', 
    'Système de navigation AR pour les musées', 
    'Develop an augmented reality-powered navigation system for museums that enhances visitor engagement through interactive 3D content and guided tours. By blending technology with culture, this project redefines how people explore and experience exhibits.', 
    'Développez un système de navigation alimenté par la réalité augmentée pour les musées qui améliore l engagement des visiteurs grâce à des contenus 3D interactifs et des visites guidées. En alliant technologie et culture, ce projet redéfinit la manière dont les gens explorent et expérimentent les expositions.', 
    'Pending'),
(2, 1, NULL, 
    'Interactive Mental Health App', 
    'Application interactive pour la santé mentale', 
    'Design an innovative app that combines motion graphics, interactive media, and AI-powered personalized mindfulness exercises. This project aims to provide accessible mental health resources through engaging visuals and adaptive therapeutic content.', 
    'Concevez une application innovante qui combine des graphismes animés, des médias interactifs et des exercices de pleine conscience personnalisés alimentés par l IA. Ce projet vise à fournir des ressources de santé mentale accessibles grâce à des visuels attrayants et un contenu thérapeutique adaptatif.', 
    'Pending'),
(2, 1, NULL, 
    'AR-Enhanced Marketing Campaigns', 
    'Campagnes marketing améliorées par la RA', 
    'Develop an augmented reality campaign for a sustainable brand, combining interactivity with eco-conscious storytelling.', 
    'Développez une campagne de réalité augmentée pour une marque durable, combinant interactivité et narration éco-responsable.', 
    'Pending'),
(2, 1, NULL, 
    'Virtual Museum Exhibit', 
    'Exposition virtuelle de musée', 
    'Create a virtual museum exhibit showcasing historical artifacts with motion-activated narrations and 3D animations.', 
    'Créez une exposition virtuelle de musée présentant des artefacts historiques avec des narrations activées par le mouvement et des animations en 3D.', 
    'Pending'),
(3, 1, NULL, 
    'Universal Accessibility Design System', 
    'Système de conception pour l accessibilité universelle', 
    'Develop a comprehensive toolkit for designing accessible digital products. This system leverages responsive design principles, WCAG-compliant components, and AI-driven testing to ensure inclusivity for people with disabilities across all digital platforms.', 
    'Développez un ensemble d outils complet pour la conception de produits numériques accessibles. Ce système utilise les principes de conception réactive, les composants conformes aux WCAG, et des tests pilotés par IA pour garantir l inclusivité des personnes handicapées sur toutes les plateformes numériques.', 
    'Pending'),
(3, 1, NULL, 
    'AI-Powered User Experience Optimization Tool', 
    'Outil d optimisation de l expérience utilisateur alimenté par l IA', 
    'Build a state-of-the-art tool that utilizes machine learning to analyze user behavior and suggest real-time design optimizations. This project enables businesses to enhance user satisfaction and engagement through data-driven insights.', 
    'Créez un outil de pointe utilisant l apprentissage automatique pour analyser le comportement des utilisateurs et suggérer des optimisations de conception en temps réel. Ce projet permet aux entreprises d améliorer la satisfaction et l engagement des utilisateurs grâce à des informations basées sur les données.', 
    'Pending'),
(3, 1, NULL, 
    'Smart City Interface', 
    'Interface pour la ville intelligente', 
    'Design an intuitive interface for smart city services that integrates real-time data on transportation, public safety, and waste management. This project combines IoT data visualization with cutting-edge UX design to simplify urban living.', 
    'Concevez une interface intuitive pour les services de la ville intelligente qui intègre des données en temps réel sur les transports, la sécurité publique et la gestion des déchets. Ce projet combine la visualisation des données IoT avec une conception UX de pointe pour simplifier la vie urbaine.', 
    'Pending'),
(4, 1, NULL, 
    'Predictive Marketing Platform', 
    'Plateforme de marketing prédictif', 
    'Leverage AI and big data analytics to create a marketing platform that predicts the most effective strategies for target audiences. This project delivers actionable insights and automates campaign optimization for maximum ROI.', 
    'Exploitez l IA et l analyse des grandes données pour créer une plateforme de marketing qui prédit les stratégies les plus efficaces pour les publics cibles. Ce projet fournit des informations exploitables et automatise l optimisation des campagnes pour un ROI maximal.', 
    'Pending'),
(4, 1, NULL, 
    'Sentiment Analysis Dashboard', 
    'Tableau de bord d analyse des sentiments', 
    'Develop a robust AI-driven dashboard that analyzes consumer sentiment in real-time from social media and reviews. With NLP capabilities and data visualization, this tool provides deep insights into brand perception and market trends.', 
    'Développez un tableau de bord robuste alimenté par l IA qui analyse les sentiments des consommateurs en temps réel à partir des médias sociaux et des avis. Avec des capacités de traitement du langage naturel (NLP) et de visualisation des données, cet outil offre des informations approfondies sur la perception de la marque et les tendances du marché.', 
    'Pending'),
(4, 1, NULL, 
    'Localized Marketing Campaign', 
    'Campagne de marketing localisée', 
    'Create a region-specific marketing campaign using advanced data analytics to tailor messaging and media. This project maximizes impact by incorporating AI-driven audience segmentation and personalized content strategies.', 
    'Créez une campagne de marketing spécifique à la région en utilisant l analyse avancée des données pour personnaliser les messages et les médias. Ce projet maximise l impact en intégrant une segmentation du public alimentée par l IA et des stratégies de contenu personnalisées.', 
    'Pending'),
(4, 1, NULL, 
    'Ecosystem Sustainability Campaign', 
    'Campagne de durabilité des écosystèmes', 
    'Develop a full-scale digital marketing campaign to promote an eco-friendly initiative. Include SEO-optimized content, social media ads, and email newsletters.', 
    'Développez une campagne de marketing numérique à grande échelle pour promouvoir une initiative écologique. Incluez du contenu optimisé pour le SEO, des publicités sur les réseaux sociaux et des newsletters par e-mail.', 
    'Pending'),
(4, 1, NULL, 
    'Global Small Business Accelerator', 
    'Accélérateur mondial pour les petites entreprises', 
    'Create a comprehensive marketing strategy for small businesses to compete globally, focusing on affordable tools and scalable solutions.', 
    'Créez une stratégie marketing complète pour les petites entreprises afin de concourir à l échelle mondiale, en vous concentrant sur des outils abordables et des solutions évolutives.', 
    'Pending'),
(5, 1, NULL, 
    'AI-Powered Risk Mitigation Tool', 
    'Outil de réduction des risques alimenté par l IA', 
    'Build a powerful AI-based tool for identifying and mitigating risks in supply chains. By leveraging predictive analytics and real-time monitoring, this project helps businesses enhance operational efficiency and prevent losses.', 
    'Créez un puissant outil basé sur l IA pour identifier et atténuer les risques dans les chaînes d approvisionnement. En exploitant l analyse prédictive et la surveillance en temps réel, ce projet aide les entreprises à améliorer l efficacité opérationnelle et à prévenir les pertes.', 
    'Pending'),
(5, 1, NULL, 
    'Health Crisis Predictive Model', 
    'Modèle prédictif de crise sanitaire', 
    'Design a cutting-edge predictive analytics model that uses historical and real-time data to identify potential healthcare crises. This project aims to strengthen preparedness and reduce mortality rates through early detection.', 
    'Concevez un modèle d analyse prédictive de pointe qui utilise des données historiques et en temps réel pour identifier les crises sanitaires potentielles. Ce projet vise à renforcer la préparation et à réduire les taux de mortalité grâce à une détection précoce.', 
    'Pending'),
(5, 1, NULL, 
    'Fraud Detection Dashboard', 
    'Tableau de bord de détection de fraude', 
    'Develop a high-tech dashboard for financial institutions to detect fraud by analyzing transaction patterns and anomalies. Integrating AI and advanced data visualization, this project ensures secure and trustworthy operations.', 
    'Développez un tableau de bord high-tech pour les institutions financières afin de détecter la fraude en analysant les schémas de transaction et les anomalies. En intégrant l IA et une visualisation avancée des données, ce projet garantit des opérations sécurisées et fiables.', 
    'Pending'),
(5, 1, NULL, 
    'Fraud Detection Dashboard', 
    'Tableau de bord de détection de fraude', 
    'Develop a dashboard for financial institutions to detect fraud by analyzing transaction patterns and anomalies', 
    'Développez un tableau de bord pour les institutions financières afin de détecter la fraude en analysant les schémas de transaction et les anomalies', 
    'Pending'),
(5, 1, NULL, 
    'Global Collaborative Workspace', 
    'Espace de travail collaboratif mondial', 
    'Create a cloud-based project management tool optimized for remote teams, integrating Agile boards and real-time resource tracking', 
    'Créez un outil de gestion de projet basé sur le cloud, optimisé pour les équipes à distance, intégrant des tableaux Agile et le suivi des ressources en temps réel', 
    'Pending'),
(5, 1, NULL, 
    'Disaster Relief Project Plan', 
    'Plan de projet pour les secours en cas de catastrophe', 
    'Develop a project plan to manage resources and coordinate efforts during a natural disaster, using Agile methodologies.', 
    'Développez un plan de projet pour gérer les ressources et coordonner les efforts lors d une catastrophe naturelle, en utilisant des méthodologies Agile.', 
    'Pending'),
(6, 1, NULL, 'Automated Network Monitoring Tool', 'Outil de Surveillance Réseau Automatisée', 
    'Develop an intelligent tool that monitors network health in real-time, detects anomalies, and provides proactive alerts to administrators. This project ensures optimal network performance using AI-powered analytics.', 
    'Développer un outil intelligent qui surveille la santé du réseau en temps réel, détecte les anomalies et fournit des alertes proactives aux administrateurs. Ce projet assure des performances optimales du réseau grâce à des analyses alimentées par l IA.', 'Pending'),
(6, 1, NULL, 'Secure Multi-Tier Architecture', 'Architecture Sécurisée Multi-Tiers', 
    'Set up a robust, multi-tier server architecture that ensures data security, high availability, and fault tolerance. This project incorporates cutting-edge encryption techniques and load-balancing mechanisms.', 
    'Mettre en place une architecture serveur robuste à plusieurs niveaux qui garantit la sécurité des données, une haute disponibilité et une tolérance aux pannes. Ce projet intègre des techniques de cryptage de pointe et des mécanismes de répartition de charge.', 'Pending'),
(6, 1, NULL, 'IoT Device Network Integration', 'Intégration de Réseau d Appareils IoT', 
    'Configure a network for managing IoT devices securely in a smart home or smart office environment.', 
    'Configurer un réseau pour gérer les appareils IoT de manière sécurisée dans un environnement de maison ou de bureau intelligent.', 'Pending'),
(7, 1, NULL, 'Self-Healing Deployment Pipeline', 'Pipeline de Déploiement Auto-Réparant', 
    'Create an advanced CI/CD pipeline that uses machine learning to detect and resolve deployment issues autonomously. This project revolutionizes development workflows with automated recovery systems.', 
    'Créer un pipeline CI/CD avancé qui utilise l apprentissage automatique pour détecter et résoudre de manière autonome les problèmes de déploiement. Ce projet révolutionne les flux de travail de développement avec des systèmes de récupération automatisés.', 'Pending'),
(7, 1, NULL, 'Scalable Microservices Architecture', 'Architecture Microservices Évolutive', 
    'Design and deploy a microservices application with Docker and Kubernetes for unparalleled scalability and fault tolerance. This project ensures high-performance enterprise applications.', 
    'Concevoir et déployer une application microservices avec Docker et Kubernetes pour une évolutivité et une tolérance aux pannes sans égal. Ce projet garantit des applications d entreprise haute performance.', 'Pending'),
(7, 1, NULL, 'Cloud-Native DevOps Toolkit', 'Kit d Outils DevOps Cloud-Natifs', 
    'Develop a toolkit to enable small businesses to adopt cloud-native DevOps practices with minimal overhead.', 
    'Développer un kit d outils pour permettre aux petites entreprises d adopter des pratiques DevOps cloud-native avec un minimum de frais généraux.', 'Pending'),
(8, 1, NULL, 'Cyberattack Investigation Simulator', 'Simulateur d Enquête sur les Cyberattaques', 
    'Develop an advanced simulation tool to train cybersecurity teams on detecting, investigating, and mitigating live cyberattacks. This tool integrates real-time scenarios, interactive training modules, and AI-driven analytics for enhanced readiness.', 
    'Développer un outil de simulation avancé pour former les équipes de cybersécurité à la détection, l investigation et la réduction des cyberattaques en direct. Cet outil intègre des scénarios en temps réel, des modules de formation interactifs et des analyses alimentées par l IA pour améliorer la préparation.', 'Pending'),
(8, 1, NULL, 'Digital Evidence Management System', 'Système de Gestion des Preuves Numériques', 
    'Create a next-generation system for securely storing, organizing, and sharing digital evidence. This project ensures compliance with legal standards while leveraging encryption and blockchain for integrity and transparency.', 
    'Créer un système de prochaine génération pour stocker, organiser et partager des preuves numériques de manière sécurisée. Ce projet garantit la conformité aux normes légales tout en utilisant le cryptage et la blockchain pour l intégrité et la transparence.', 'Pending'),
(8, 1, NULL, 'Ransomware Recovery Playbook', 'Manuel de Récupération après Ransomware', 
    'Design a comprehensive playbook detailing steps to analyze, mitigate, and recover from ransomware attacks.', 
    'Concevoir un manuel complet détaillant les étapes pour analyser, atténuer et récupérer après des attaques de ransomware.', 'Pending'),
(12, 1, NULL, 'NFT Marketplace for Cultural Artifacts', 'Marché NFT pour Artefacts Culturels', 
    'Build a blockchain-powered NFT marketplace to digitally preserve and promote cultural artifacts. This platform ensures authenticity and transparency in transactions while providing a unique medium to showcase cultural heritage.', 
    'Construire un marché NFT alimenté par la blockchain pour préserver numériquement et promouvoir les artefacts culturels. Cette plateforme garantit l authenticité et la transparence des transactions tout en offrant un moyen unique de mettre en valeur le patrimoine culturel.', 'Pending'),
(12, 1, NULL, 'Green Energy Tokenization', 'Tokenisation de l Énergie Verte', 
    'Develop a blockchain-based platform to tokenize green energy credits, enabling secure and transparent trading. This project promotes sustainability by leveraging decentralized finance (DeFi) innovations.', 
    'Développer une plateforme basée sur la blockchain pour tokeniser les crédits d énergie verte, permettant un trading sécurisé et transparent. Ce projet promeut la durabilité en tirant parti des innovations de la finance décentralisée (DeFi).', 'Pending'),
(12, 1, NULL, 'Decentralized Marketplace', 'Marché Décentralisé', 
    'Build a blockchain-based marketplace for peer-to-peer transactions, integrating cryptocurrency payments and smart contracts.', 
    'Construire un marché basé sur la blockchain pour des transactions de pair à pair, intégrant des paiements en cryptomonnaie et des contrats intelligents.', 'Pending'),
(12, 1, NULL, 'Decentralized Identity Verification System', 'Système de Vérification d Identité Décentralisé', 
    'Build a blockchain-based identity verification platform that allows users to store and control their identity data securely. Users can grant access to specific parties (banks, employers, etc.) without relying on centralized databases.', 
    'Construire une plateforme de vérification d identité basée sur la blockchain qui permet aux utilisateurs de stocker et de contrôler leurs données d identité de manière sécurisée. Les utilisateurs peuvent accorder un accès à des parties spécifiques (banques, employeurs, etc.) sans dépendre des bases de données centralisées.', 'Pending'),
(12, 1, NULL, 'Voting System on Blockchain', 'Système de Vote sur Blockchain', 
    'Develop a secure and transparent voting system based on blockchain, ensuring votes are immutable and verifiable.', 
    'Développer un système de vote sécurisé et transparent basé sur la blockchain, garantissant que les votes sont immuables et vérifiables.', 'Pending'),   
(15, 1, NULL, 'AI-Powered Mental Health Support System', 'Système de Soutien en Santé Mentale Alimenté par l IA', 
    'Create a platform that uses AI and NLP to analyze users mental health concerns, provide therapeutic exercises, and match users with appropriate counselors. Incorporate real-time chat functionality and AI-driven conversation simulations for a 24/7 support system.', 
    'Créez une plateforme qui utilise l IA et le NLP pour analyser les préoccupations de santé mentale des utilisateurs, fournir des exercices thérapeutiques et associer les utilisateurs à des conseillers appropriés. Intégrez une fonctionnalité de chat en temps réel et des simulations de conversation alimentées par l IA pour un système de soutien 24h/24 et 7j/7.', 'Pending'),
(15, 1, NULL, 'Global Disaster Response Platform (Real-time Web App & API Integration)', 'Plateforme de Réponse aux Catastrophes Mondiales (Application Web en Temps Réel & Intégration API)', 
    'Build a web platform that connects disaster responders, local governments, and affected citizens in real time. It can track incidents, display real-time geolocation data, and connect with emergency response teams. Integrate APIs for weather forecasting, social media, and real-time satellite data for crisis management.', 
    'Construisez une plateforme web qui connecte les intervenants en cas de catastrophe, les gouvernements locaux et les citoyens affectés en temps réel. Elle peut suivre les incidents, afficher des données de géolocalisation en temps réel et se connecter aux équipes de réponse aux urgences. Intégrez des API pour les prévisions météorologiques, les réseaux sociaux et les données satellites en temps réel pour la gestion des crises.', 'Pending'),
(9, 1, NULL, 'Smart City Vulnerability Assessment', 'Évaluation de la Vulnérabilité des Villes Intelligentes', 
    'Conduct a penetration test on a smart city simulation to identify security gaps in IoT devices and network protocols.', 
    'Réaliser un test de pénétration sur une simulation de ville intelligente pour identifier les lacunes de sécurité dans les appareils IoT et les protocoles réseau.', 'Pending'),
(9, 1, NULL, 'AI-Powered Penetration Toolkit', 'Kit d Outils de Pénétration Alimenté par l IA', 
    'Build a toolkit that leverages machine learning to identify vulnerabilities in large-scale IT environments.', 
    'Construisez un kit d outils qui exploite l apprentissage automatique pour identifier les vulnérabilités dans les environnements informatiques à grande échelle.', 'Pending'), 
(9, 1, NULL, 'Banking Application Security Audit', 'Audit de Sécurité de l Application Bancaire', 
    'Perform a full security audit on a simulated banking app, focusing on transaction safety and user data protection', 
    'Effectuer un audit de sécurité complet sur une application bancaire simulée, en se concentrant sur la sécurité des transactions et la protection des données des utilisateurs', 'Pending'), 
(16, 1, NULL, 'Language Learning Mobile App', 'Application Mobile d Apprentissage des Langues', 
    'Create an intuitive and interactive mobile app for language learning, featuring gamified lessons, AI-driven progress tracking, and real-time speech feedback. This project aims to make language acquisition engaging and personalized.', 
    'Créez une application mobile intuitive et interactive pour l apprentissage des langues, avec des leçons gamifiées, un suivi des progrès alimenté par l IA et des retours en temps réel sur la parole. Ce projet vise à rendre l acquisition de langues engageante et personnalisée.', 'Pending'),
(16, 1, NULL, 'Smart Agriculture Assistant App', 'Application d Assistant Agricole Intelligent', 
    'Design a cutting-edge mobile app that integrates IoT sensors and AI algorithms to help farmers monitor crop health, optimize irrigation, and predict harvest times. This project advances precision agriculture.', 
    'Concevez une application mobile de pointe qui intègre des capteurs IoT et des algorithmes d IA pour aider les agriculteurs à surveiller la santé des cultures, optimiser l irrigation et prédire les temps de récolte. Ce projet fait progresser l agriculture de précision.', 'Pending'),
(14, 1, NULL, 'Autonomous Delivery Drone', 'Drone de Livraison Autonome', 
    'Build an autonomous drone system equipped with GPS navigation, real-time obstacle detection, and AI optimization for efficient package delivery. This project revolutionizes logistics by reducing human intervention and enhancing delivery speed.', 
    'Construisez un système de drone autonome équipé de navigation GPS, de détection d obstacles en temps réel et d optimisation par IA pour une livraison de colis efficace. Ce projet révolutionne la logistique en réduisant l intervention humaine et en améliorant la vitesse de livraison.', 'Pending'),
(14, 1, NULL, 'Drone-Based Disaster Response System', 'Système de Réponse aux Catastrophes Basé sur Drone', 
    'Develop a sophisticated drone system for delivering medical supplies and conducting search-and-rescue missions during natural disasters. This project combines advanced navigation algorithms with real-time monitoring for life-saving operations.', 
    'Développez un système sophistiqué de drones pour la livraison de fournitures médicales et la conduite de missions de recherche et de sauvetage lors de catastrophes naturelles. Ce projet combine des algorithmes de navigation avancés avec une surveillance en temps réel pour des opérations de sauvetage.', 'Pending'),
(14, 1, NULL, 'Agricultural Drone for Crop Monitoring', 'Drone Agricole pour la Surveillance des Cultures', 
    'Create a drone equipped with cameras and sensors to monitor crop health and soil conditions, providing actionable insights to farmers', 
    'Créez un drone équipé de caméras et de capteurs pour surveiller la santé des cultures et les conditions du sol, fournissant des informations exploitables aux agriculteurs', 'Pending'),
(13, 1, NULL, 'Smart Agriculture System', 'Système Agricole Intelligent', 
    'Develop an IoT-powered system to monitor soil conditions, temperature, and moisture levels in real time. By providing actionable insights and enabling automated irrigation, this project empowers farmers to achieve sustainable agriculture.', 
    'Développez un système alimenté par IoT pour surveiller les conditions du sol, la température et les niveaux d humidité en temps réel. En fournissant des informations exploitables et en permettant l irrigation automatisée, ce projet permet aux agriculteurs d atteindre une agriculture durable.', 'Pending'),
(13, 1, NULL, 'IoT-Enabled Home Automation', 'Automatisation Domestique Alimentée par IoT', 
    'Create a state-of-the-art home automation system to control lighting, thermostats, and security devices via a mobile app. This project integrates IoT protocols with AI-powered personalization for convenience and energy efficiency.', 
    'Créez un système d automatisation domestique de pointe pour contrôler l éclairage, les thermostats et les dispositifs de sécurité via une application mobile. Ce projet intègre des protocoles IoT avec une personnalisation alimentée par IA pour plus de commodité et d efficacité énergétique.', 'Pending'),
(13, 1, NULL, 'IoT Health Monitoring Wearables', 'Vêtements Connectés de Surveillance de la Santé IoT', 
    'Design a wearable device that tracks vital health metrics such as heart rate, body temperature, and blood pressure, sending the data to a cloud server for analysis', 
    'Concevez un appareil portable qui suit des indicateurs de santé vitaux tels que la fréquence cardiaque, la température corporelle et la pression artérielle, envoyant les données à un serveur cloud pour analyse', 'Pending'),
(13, 1, NULL, 'Construction of a 3D printer', 'Construction d une Imprimante 3D', 
    'This project focuses on building a fully functional 3D printer from scratch. The printer will use a combination of mechanical, electrical, and software components to produce 3D objects based on digital models. The project will emphasize precision in construction, calibration, and programming to ensure accurate and reliable printing.', 
    'Ce projet consiste à construire une imprimante 3D entièrement fonctionnelle à partir de zéro. L imprimante utilisera une combinaison de composants mécaniques, électriques et logiciels pour produire des objets 3D basés sur des modèles numériques. Le projet mettra l accent sur la précision de la construction, de la calibration et de la programmation pour garantir une impression précise et fiable.', 'Pending'),
(13, 1, NULL, 'Construction of a digital screen display using LEDs', 'Construction d un Écran Numérique à l Aide de LED', 
    'This project involves designing and building a functional digital screen using an array of LEDs. The goal is to create a dynamic display capable of showcasing text, images, or animations. The project focuses on integrating hardware components like LED matrices and microcontrollers with appropriate software for control and customization.', 
    'Ce projet consiste à concevoir et construire un écran numérique fonctionnel utilisant un ensemble de LED. L objectif est de créer un affichage dynamique capable de présenter du texte, des images ou des animations. Le projet se concentre sur l intégration des composants matériels comme les matrices de LED et les microcontrôleurs avec le logiciel approprié pour le contrôle et la personnalisation.', 'Pending'),
(17, 1, NULL, 'AI-Powered Personalized Education Assistant', 'Assistant Éducatif Personnalisé Alimenté par l IA', 
    'Build an AI-driven education assistant that adapts to individual learning styles, delivering customized lessons, quizzes, and real-time feedback. By leveraging machine learning and NLP, this project redefines the education landscape.', 
    'Créez un assistant éducatif alimenté par l IA qui s adapte aux styles d apprentissage individuels, en offrant des leçons personnalisées, des quiz et des retours en temps réel. En exploitant l apprentissage automatique et le NLP, ce projet redéfinit le paysage éducatif.', 'Pending'),
(17, 1, NULL, 'Real-Time Traffic Data Analysis', 'Analyse des Données de Trafic en Temps Réel', 
    'Create a big data processing system that analyzes real-time traffic data from IoT sensors and cameras to predict congestion, suggest optimal routes, and provide insights for urban planning. This project advances smart city solutions.', 
    'Créez un système de traitement de données massives qui analyse les données de trafic en temps réel provenant de capteurs IoT et de caméras pour prédire la congestion, suggérer des itinéraires optimaux et fournir des informations pour la planification urbaine. Ce projet fait progresser les solutions de villes intelligentes.', 'Pending'),
(18, 1, NULL, 'Image Editing Software', 'Logiciel de Retouche d Image', 
    'Develop a lightweight and intuitive desktop image editor featuring advanced cropping, filtering, and overlay tools. This project provides an accessible and powerful alternative for quick and professional-grade image editing.', 
    'Développez un éditeur d images de bureau léger et intuitif avec des outils de découpe, de filtrage et de superposition avancés. Ce projet propose une alternative accessible et puissante pour une retouche d image rapide et de qualité professionnelle.', 'Pending'),
(18, 1, NULL, 'Real-time Language Translation Desktop App', 'Application de Traduction Linguistique en Temps Réel pour Bureau', 
    'Create a multi-platform desktop application that delivers real-time language translation and transcription. Leveraging NLP and AI models, this project facilitates seamless global communication.', 
    'Créez une application de bureau multiplateforme qui offre une traduction linguistique et une transcription en temps réel. En exploitant les modèles NLP et l IA, ce projet facilite une communication mondiale fluide.', 'Pending'),
(10, 1, NULL, 'Quantum-Resistant Messaging System', 'Système de Messagerie Résistant aux Quantums', 
    'Design a state-of-the-art secure messaging platform that incorporates quantum-resistant cryptographic algorithms. This project ensures future-proof communication systems by mitigating the risks posed by quantum computing advancements.', 
    'Concevez une plateforme de messagerie sécurisée de pointe qui intègre des algorithmes cryptographiques résistants aux quantums. Ce projet garantit des systèmes de communication à l épreuve du futur en atténuant les risques posés par les avancées de l informatique quantique.', 'Pending'),
(10, 1, NULL, 'Encrypted Cloud Storage Service', 'Service de Stockage Cloud Chiffré', 
    'Develop a cutting-edge cloud storage solution with end-to-end encryption and zero-knowledge security principles. This project prioritizes user data privacy and security in an increasingly interconnected world.', 
    'Développez une solution de stockage cloud de pointe avec un chiffrement de bout en bout et des principes de sécurité à connaissance zéro. Ce projet privilégie la confidentialité des données des utilisateurs et la sécurité dans un monde de plus en plus interconnecté.', 'Pending'),
(11, 1, NULL, 'Drone Communication Security System', 'Système de Sécurité des Communications de Drones', 
    'Develop a robust security framework for drones to ensure secure communication during critical missions. This project integrates advanced encryption protocols and real-time threat detection to protect drone operations.', 
    'Développez un cadre de sécurité robuste pour les drones afin d assurer une communication sécurisée pendant les missions critiques. Ce projet intègre des protocoles de cryptage avancés et une détection de menaces en temps réel pour protéger les opérations des drones.', 'Pending'),
(11, 1, NULL, 'Secure Smart Home Network', 'Réseau Domestique Intelligent Sécurisé', 
    'Design a secure wireless network architecture for IoT-enabled smart homes. This project focuses on mitigating risks such as data breaches and unauthorized access, ensuring user privacy and safety.', 
    'Concevez une architecture de réseau sans fil sécurisé pour les maisons intelligentes connectées par IoT. Ce projet se concentre sur l atténuation des risques tels que les violations de données et les accès non autorisés, garantissant la confidentialité et la sécurité des utilisateurs.', 'Pending'),
(11, 1, NULL, 'Campus Wi-Fi Threat Detection', 'Détection des Menaces du Wi-Fi du Campus', 
    'Create a tool to monitor and mitigate security threats in large-scale campus Wi-Fi networks', 
    'Créez un outil pour surveiller et atténuer les menaces de sécurité dans les réseaux Wi-Fi de campus à grande échelle', 'Pending');

